# Generated by Django 4.2.6 on 2023-10-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipes',
            name='instructions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cal',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='menu',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='restriccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
